<?php
/**
 * Standalone test script — validates ihf-migration-setup plugin logic.
 * Run from repo root: php test-plugin.php
 * No WordPress required.
 */

$pass = 0;
$fail = 0;

function ok( string $label, bool $result, string $detail = '' ): void {
    global $pass, $fail;
    if ( $result ) {
        echo "  PASS  {$label}\n";
        $pass++;
    } else {
        echo "  FAIL  {$label}" . ( $detail ? " — {$detail}" : '' ) . "\n";
        $fail++;
    }
}

// ── 1. PHP syntax check on all plugin files ────────────────────────────────────
echo "\n=== PHP Syntax ===\n";
$files = [
    'ihf-migration-setup/ihf-migration-setup.php',
    'ihf-migration-setup/CLAUDE.md',  // not PHP but check it exists
];
foreach ( [ 'ihf-migration-setup/ihf-migration-setup.php' ] as $f ) {
    $out = shell_exec( "php -l " . escapeshellarg( $f ) . " 2>&1" );
    ok( $f, strpos( $out, 'No syntax errors' ) !== false, trim( $out ) );
}

// ── 2. All 4 WPCode snippet PHP blocks syntax-check cleanly ───────────────────
echo "\n=== Snippet PHP Syntax ===\n";
// Extract snippets from plugin by requiring a mock WordPress environment
$snippets_raw = file_get_contents( 'ihf-migration-setup/ihf-migration-setup.php' );

// Pull out each <<<'PHP' ... PHP heredoc block
preg_match_all( "/'code'\s*=>\s*<<<'PHP'\n(.*?)PHP,/s", $snippets_raw, $matches );
$snippet_codes = $matches[1] ?? [];
ok( 'Found 4 WPCode snippets', count( $snippet_codes ) === 4, 'Found ' . count( $snippet_codes ) );

foreach ( $snippet_codes as $i => $code ) {
    $tmp = sys_get_temp_dir() . "/ims_snippet_{$i}.php";
    file_put_contents( $tmp, "<?php\n" . $code );
    $out = shell_exec( "php -l " . escapeshellarg( $tmp ) . " 2>&1" );
    ok( "Snippet " . ( $i + 1 ) . " syntax", strpos( $out, 'No syntax errors' ) !== false, trim( $out ) );
    unlink( $tmp );
}

// ── 3. CLAUDE.md template file exists and has required markers ────────────────
echo "\n=== CLAUDE.md Template ===\n";
$template = file_get_contents( 'ihf-migration-setup/CLAUDE.md' );
ok( 'Template file exists', $template !== false );
ok( 'Has MARKET_IDS_START marker', strpos( $template, '<!-- MARKET_IDS_START -->' ) !== false );
ok( 'Has MARKET_IDS_END marker',   strpos( $template, '<!-- MARKET_IDS_END -->' ) !== false );
ok( 'Has URL Redirect Map',        strpos( $template, '## URL Redirect Map' ) !== false );
ok( 'Has iHF Shortcode Reference', strpos( $template, '## iHomefinder Shortcode Reference' ) !== false );
ok( 'Has IDX Widget mapping',      strpos( $template, '## IDX Broker Widget' ) !== false );
ok( 'Has Key Rules',               strpos( $template, '## Key Rules' ) !== false );
ok( 'Has 10-step workflow',        strpos( $template, 'Step 10' ) !== false );
ok( 'Step 3 uses full subdomain for /i/',  strpos( $template, 'search.[domain].com/i/' ) !== false );
$step9_start = strpos( $template, '**Step 9:' );
$step9_end   = strpos( $template, '**Step 10:', $step9_start );
$step9_text  = substr( $template, $step9_start, $step9_end - $step9_start );
ok( 'Step 9 checks idx-broker-platinum',  strpos( $step9_text, 'idx-broker-platinum' ) !== false );
ok( 'Rule 5 no longer blocks widget replacement', strpos( $template, 'Don\'t replace community' ) === false );

// ── 4. CLAUDE.md template injection ───────────────────────────────────────────
echo "\n=== Template Injection ===\n";
$sample_markets = [
    [ 'name' => 'Aliso Viejo Homes for Sale',    'id' => '2996465', 'url' => '/listing-report/aliso-viejo-homes-for-sale/2996465/' ],
    [ 'name' => 'Aliso Viejo Listings $0-$500k', 'id' => '2996466', 'url' => '/listing-report/aliso-viejo-listings-0-500000/2996466/' ],
];

$market_table = "| Market Name | ID | listing-report URL |\n|---|---|---|\n";
foreach ( $sample_markets as $m ) {
    $market_table .= "| {$m['name']} | " . ( $m['id'] ?: '—' ) . " | " . ( $m['url'] ?: '—' ) . " |\n";
}

$site_name = 'Test Agent Site';
$site_url  = 'https://test.mystagingwebsite.com';
$market_block = "### {$site_name}\n\nSite: {$site_url}\n\n{$market_table}";
$replacement  = "<!-- MARKET_IDS_START -->\n{$market_block}\n<!-- MARKET_IDS_END -->";
$injected = preg_replace_callback(
    '/<!-- MARKET_IDS_START -->.*?<!-- MARKET_IDS_END -->/s',
    function() use ( $replacement ) { return $replacement; },
    $template
);

// Verify placeholder is gone and the injected block is between the markers
$start_pos    = strpos( $injected, '<!-- MARKET_IDS_START -->' );
$end_pos      = strpos( $injected, '<!-- MARKET_IDS_END -->' );
$between      = substr( $injected, $start_pos, $end_pos - $start_pos );
ok( 'Injection replaced placeholder',    strpos( $between, '(Generated by iHF Migration Setup' ) === false );
ok( 'Injection contains site name',      strpos( $injected, 'Test Agent Site' ) !== false );
ok( 'Injection contains market name',    strpos( $injected, 'Aliso Viejo Homes for Sale' ) !== false );
ok( 'Injection contains market ID',      strpos( $injected, '2996465' ) !== false );
ok( 'Injection contains listing-report URL', strpos( $injected, '/listing-report/aliso-viejo-homes-for-sale/2996465/' ) !== false );
ok( 'Markers preserved after injection', strpos( $injected, '<!-- MARKET_IDS_START -->' ) !== false );
ok( 'Full instructions still present',   strpos( $injected, '## URL Redirect Map' ) !== false );

// ── 5. URL normalisation ───────────────────────────────────────────────────────
echo "\n=== URL Normalisation ===\n";
function mock_wp_parse_url( string $url ): array {
    return parse_url( $url ) ?: [];
}
function normalise_url( string $url ): string {
    if ( $url && preg_match( '#^https?://#', $url ) ) {
        $parsed = mock_wp_parse_url( $url );
        return ( $parsed['path'] ?? '/' ) . ( isset( $parsed['query'] ) ? '?' . $parsed['query'] : '' );
    }
    return $url;
}
ok( 'Absolute URL stripped to relative', normalise_url( 'https://cesipagano.com/listing-report/aliso-viejo-homes-for-sale/2996465/' ) === '/listing-report/aliso-viejo-homes-for-sale/2996465/' );
ok( 'Relative URL unchanged',            normalise_url( '/listing-report/aliso-viejo-homes-for-sale/2996465/' ) === '/listing-report/aliso-viejo-homes-for-sale/2996465/' );
ok( 'Empty URL unchanged',               normalise_url( '' ) === '' );
ok( 'URL with query string preserved',   normalise_url( 'https://cesipagano.com/homes-for-sale-search/?minprice=500000' ) === '/homes-for-sale-search/?minprice=500000' );

// ── 6. App password space-stripping ───────────────────────────────────────────
echo "\n=== App Password Formatting ===\n";
$wp_formatted = 'AbCd EfGh IjKl MnOp QrSt UvWx';  // WP display format
$stripped = str_replace( ' ', '', $wp_formatted );
ok( 'Spaces stripped from WP app password', $stripped === 'AbCdEfGhIjKlMnOpQrStUvWx' );
ok( 'Result is alphanumeric only',           ctype_alnum( $stripped ) );

// ── 7. Config JSON structure ───────────────────────────────────────────────────
echo "\n=== Config JSON ===\n";
$config = [
    'mcpServers' => [
        'wordpress' => [
            'command' => 'npx',
            'args'    => [ '-y', '@automattic/mcp-server-wordpress' ],
            'env'     => [
                'WP_SITE_URL'     => 'https://test.mystagingwebsite.com',
                'WP_USERNAME'     => 'claude-mcp',
                'WP_APP_PASSWORD' => 'AbCdEfGhIjKlMnOpQrStUvWx',
            ],
        ],
    ],
];
$json = json_encode( $config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
$decoded = json_decode( $json, true );
ok( 'Config JSON is valid',              $decoded !== null );
ok( 'Config has mcpServers key',         isset( $decoded['mcpServers'] ) );
ok( 'Config has wordpress server',       isset( $decoded['mcpServers']['wordpress'] ) );
ok( 'Config has WP_SITE_URL',            isset( $decoded['mcpServers']['wordpress']['env']['WP_SITE_URL'] ) );
ok( 'Config has WP_APP_PASSWORD',        isset( $decoded['mcpServers']['wordpress']['env']['WP_APP_PASSWORD'] ) );
ok( 'App password has no spaces',        strpos( $decoded['mcpServers']['wordpress']['env']['WP_APP_PASSWORD'], ' ' ) === false );

// ── 8. Zip contains required files ────────────────────────────────────────────
echo "\n=== Plugin Zip Contents ===\n";
$zip_out = shell_exec( 'unzip -l ihf-migration-setup.zip 2>&1' );
ok( 'Zip contains main PHP file',   strpos( $zip_out, 'ihf-migration-setup.php' ) !== false );
ok( 'Zip contains CLAUDE.md',       strpos( $zip_out, 'CLAUDE.md' ) !== false );
ok( 'Zip contains admin.js',        strpos( $zip_out, 'admin.js' ) !== false );
ok( 'Zip contains admin.css',       strpos( $zip_out, 'admin.css' ) !== false );

// ── Summary ────────────────────────────────────────────────────────────────────
echo "\n";
$total = $pass + $fail;
echo "=== Results: {$pass}/{$total} passed" . ( $fail ? " — {$fail} FAILED" : ' — all good' ) . " ===\n\n";
exit( $fail > 0 ? 1 : 0 );
